name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.12']
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e .

      - name: Run example script
        run: python example/example.py

      - name: Check packaging metadata
        run: python setup.py check

      - name: Verify modules compile
        run: python -m compileall printx example
